In [1]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

print(' Data loaded successfully!')

 Data loaded successfully!

In [2]:
#load data as df
df = pd.read_csv('customer_shopping_behavior.csv')

In [7]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [8]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [10]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [13]:
df.shape

(3900, 18)

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
df['Age']

0       55
1       19
2       50
3       21
4       45
        ..
3895    40
3896    52
3897    46
3898    44
3899    52
Name: Age, Length: 3900, dtype: int64

In [43]:
df['Season']

0       Winter
1       Winter
2       Spring
3       Spring
4       Spring
         ...
3895    Summer
3896    Spring
3897    Spring
3898    Summer
3899    Spring
Name: Season, Length: 3900, dtype: object

In [13]:
df[['Age','Gender','Size']]

      Age  Gender Size
0      55    Male    L
1      19    Male    L
2      50    Male    S
3      21    Male    M
4      45    Male    M
...   ...     ...  ...
3895   40  Female    L
3896   52  Female    L
3897   46  Female    L
3898   44  Female    S
3899   52  Female    M

[3900 rows x 3 columns]

In [15]:
df.loc[0:5,['Age','Gender','Size']] #prints 0 to 5

   Age Gender Size
0   55   Male    L
1   19   Male    L
2   50   Male    S
3   21   Male    M
4   45   Male    M
5   46   Male    M

In [16]:
df.iloc[0:5,0:3] #prints 5 rows that is 01234

   Customer ID  Age Gender
0            1   55   Male
1            2   19   Male
2            3   50   Male
3            4   21   Male
4            5   45   Male

In [21]:
Male_customers = df[df['Gender'] == 'Male']
print('Male customers:', len(Male_customers))

Male customers: 2652

In [22]:
Female_customers = df[df['Gender'] == 'Female']
print('Female customers:', len(Female_customers))

Female customers: 1248

In [28]:
High_spenders = df[df['Purchase Amount (USD)']>80]
High_spenders[['Customer ID' ,'Age','Gender','Size','Purchase Amount (USD)']].head(10)

    Customer ID  Age Gender Size  Purchase Amount (USD)
3             4   21   Male    M                     90
6             7   63   Male    M                     85
8             9   26   Male    L                     97
15           16   64   Male    M                     81
19           20   66   Male    M                     90
23           24   31   Male   XL                     88
28           29   54   Male    M                     94
34           35   36   Male    L                     91
42           43   20   Male    M                    100
54           55   47   Male    M                     94

In [31]:
Low_spenders = df[df['Purchase Amount (USD)']<30]
Low_spenders[['Customer ID' ,'Age','Gender','Size','Purchase Amount (USD)']].head(10)

    Customer ID  Age Gender Size  Purchase Amount (USD)
5             6   46   Male    M                     20
24           25   18   Male    M                     22
25           26   18   Male    M                     25
26           27   38   Male    M                     20
45           46   50   Male   XL                     21
50           51   49   Male    M                     28
52           53   42   Male    M                     20
53           54   29   Male    S                     24
55           56   40   Male    M                     28
62           63   30   Male    S                     21

In [42]:
High_Male_customers = df[(df['Gender'] == 'Male') & (df['Purchase Amount (USD)']>80)]
print('High_purchase_Male_customers:', len(High_Male_customers))

High_purchase_Male_customers: 659

In [35]:
High_Female_customers = df[(df['Gender'] == 'Female') & (df['Purchase Amount (USD)']>80)]
print('High_purchase_Female_customers:', len(High_Female_customers))

High_purchase_Female_customers: 319

In [47]:
Seasons = ['Winter','Summer']
Seasons_purchase = df[df['Season'].isin(Seasons)]
print('selected seasonal purchase:',len(Seasons_purchase))

selected seasonal purchase: 1926

In [54]:
Missing_ratings = df[df['Review Rating'].isnull()]
print(len(Missing_ratings)) #finding null

37

In [58]:
avg_review_rating = df['Review Rating'].mean()
df['Review Rating'] = df['Review Rating'].fillna(avg_review_rating)
print(df[df['Review Rating'] == avg_review_rating])

      Customer ID  Age Gender Item Purchased     Category  \
38             39   29   Male          Dress     Clothing
50             51   49   Male         Blouse     Clothing
80             81   19   Male        Sandals     Footwear
96             97   32   Male         Gloves  Accessories
262           263   37   Male          Pants     Clothing
330           331   46   Male        Sweater     Clothing
356           357   56   Male          Pants     Clothing
383           384   50   Male     Sunglasses  Accessories
419           420   53   Male         Shorts     Clothing
442           443   29   Male     Sunglasses  Accessories
452           453   45   Male          Pants     Clothing
460           461   64   Male          Shoes     Footwear
491           492   49   Male           Coat    Outerwear
512           513   19   Male         Gloves  Accessories
560           561   25   Male        Jewelry  Accessories
628           629   69   Male        Sweater     Clothing
799           800   55   Male           Belt  Accessories
829           830   42   Male          Socks     Clothing
861           862   46   Male          Skirt     Clothing
888           889   49   Male          Scarf  Accessories
1072         1073   48   Male         Shorts     Clothing
1109         1110   66   Male         Hoodie     Clothing
1124         1125   42   Male        Sweater     Clothing
1134         1135   62   Male        T-shirt     Clothing
1151         1152   41   Male         Blouse     Clothing
1176         1177   36   Male          Dress     Clothing
1189         1190   64   Male          Shirt     Clothing
1208         1209   20   Male          Boots     Footwear
1220         1221   67   Male         Gloves  Accessories
1230         1231   25   Male            Hat  Accessories
1247         1248   65   Male        T-shirt     Clothing
1292         1293   26   Male           Belt  Accessories
1313         1314   70   Male          Shoes     Footwear
1326         1327   40   Male          Shoes     Footwear
1334         1335   46   Male           Coat    Outerwear
1341         1342   26   Male         Hoodie     Clothing
1370         1371   27   Male          Scarf  Accessories

      Purchase Amount (USD)        Location Size     Color  Season  \
38                       37         Florida    M       Red  Winter
50                       28        Maryland    M       Red  Spring
80                       72        New York   XL      Blue  Summer
96                       73        Delaware    S      Gold  Spring
262                      40          Hawaii    M      Teal  Summer
330                      51    North Dakota    M     Beige  Winter
356                      80          Nevada    L     Black  Spring
383                      77   West Virginia    S   Magenta    Fall
419                      91            Utah    S      Teal  Winter
442                      69        Michigan    M     Olive    Fall
452                      45        Missouri    M    Violet  Summer
460                      65  South Carolina    L      Teal  Summer
491                      69         Vermont    M    Silver  Summer
512                      49        New York    L     Peach  Winter
560                      48       Louisiana    L       Red    Fall
628                      85   Massachusetts    M     White    Fall
799                      55          Nevada    L     Brown  Summer
829                      57           Idaho    S    Silver  Spring
861                     100        Virginia   XL     Green  Spring
888                      77   New Hampshire    S      Gold  Spring
1072                     92           Idaho    L      Gold    Fall
1109                     97        Oklahoma    L    Violet  Winter
1124                     20            Iowa    M    Orange  Spring
1134                     81       Wisconsin    M     Brown  Summer
1151                     86            Ohio    M      Gray  Spring
1176                     83          Oregon    M       Red  Winter
1189                     97        Arkansas   XL      Teal  Summer
1208                    100       Wisconsin    S       Red  Winter
1220                     64        Kentucky    M     Green  Winter
1230                     80        Illinois    L     Brown  Spring
1247                     99        Virginia    M  Charcoal  Spring
1292                     61        Kentucky    M    Maroon  Summer
1313                     28        Missouri    M  Lavender  Summer
1326                     50           Texas    M    Indigo  Spring
1334                     52   West Virginia    S     White  Spring
1341                     27    Rhode Island   XL    Yellow    Fall
1370                     67         Montana    L     Peach  Summer

      Review Rating Subscription Status   Shipping Type Discount Applied  \
38         3.750065                 Yes  2-Day Shipping              Yes
50         3.750065                 Yes    Store Pickup              Yes
80         3.750065                 Yes    Store Pickup              Yes
96         3.750065                 Yes         Express              Yes
262        3.750065                 Yes    Next Day Air              Yes
330        3.750065                 Yes         Express              Yes
356        3.750065                 Yes        Standard              Yes
383        3.750065                 Yes        Standard              Yes
419        3.750065                 Yes   Free Shipping              Yes
442        3.750065                 Yes    Store Pickup              Yes
452        3.750065                 Yes         Express              Yes
460        3.750065                 Yes    Store Pickup              Yes
491        3.750065                 Yes  2-Day Shipping              Yes
512        3.750065                 Yes    Next Day Air              Yes
560        3.750065                 Yes   Free Shipping              Yes
628        3.750065                 Yes  2-Day Shipping              Yes
799        3.750065                 Yes   Free Shipping              Yes
829        3.750065                 Yes  2-Day Shipping              Yes
861        3.750065                 Yes  2-Day Shipping              Yes
888        3.750065                 Yes         Express              Yes
1072       3.750065                  No         Express              Yes
1109       3.750065                  No    Next Day Air              Yes
1124       3.750065                  No         Express              Yes
1134       3.750065                  No         Express              Yes
1151       3.750065                  No         Express              Yes
1176       3.750065                  No   Free Shipping              Yes
1189       3.750065                  No   Free Shipping              Yes
1208       3.750065                  No  2-Day Shipping              Yes
1220       3.750065                  No         Express              Yes
1230       3.750065                  No        Standard              Yes
1247       3.750065                  No         Express              Yes
1292       3.750065                  No   Free Shipping              Yes
1313       3.750065                  No   Free Shipping              Yes
1326       3.750065                  No   Free Shipping              Yes
1334       3.750065                  No    Store Pickup              Yes
1341       3.750065                  No        Standard              Yes
1370       3.750065                  No  2-Day Shipping              Yes

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
38               Yes                  44          Venmo         Every 3 Months
50               Yes                  39     Debit Card              Bi-Weekly
80               Yes                  24    Credit Card         Every 3 Months
96               Yes                  43          Venmo         Every 3 Months
262              Yes                   6     Debit Card               Annually
330              Yes                  43          Venmo              Bi-Weekly
356              Yes                  27           Cash                 Weekly
383              Yes                   6         PayPal              Quarterly
419              Yes                  14    Credit Card         Every 3 Months
442              Yes                  31    Credit Card              Quarterly
452              Yes                  39         PayPal            Fortnightly
460              Yes                  27  Bank Transfer                 Weekly
491              Yes                  24    Credit Card              Bi-Weekly
512              Yes                   2  Bank Transfer                Monthly
560              Yes                  12     Debit Card               Annually
628              Yes                  29    Credit Card                Monthly
799              Yes                  31         PayPal               Annually
829              Yes                  14    Credit Card            Fortnightly
861              Yes                  35    Credit Card         Every 3 Months
888              Yes                  44           Cash               Annually
1072             Yes                  34     Debit Card            Fortnightly
1109             Yes                   2          Venmo                 Weekly
1124             Yes                  40           Cash              Quarterly
1134             Yes                   2          Venmo         Every 3 Months
1151             Yes                  24    Credit Card                 Weekly
1176             Yes                  39         PayPal              Quarterly
1189             Yes                  28     Debit Card               Annually
1208             Yes                   8     Debit Card               Annually
1220             Yes                  36  Bank Transfer              Quarterly
1230             Yes                  49          Venmo                Monthly
1247             Yes                  18          Venmo              Bi-Weekly
1292             Yes                  42  Bank Transfer               Annually
1313             Yes                  23    Credit Card              Bi-Weekly
1326             Yes                  17           Cash                Monthly
1334             Yes                  12          Venmo                Monthly
1341             Yes                  31  Bank Transfer              Quarterly
1370             Yes                  41  Bank Transfer         Every 3 Months

In [59]:
Missing_ratings = df[df['Review Rating'].isnull()]
print(len(Missing_ratings)) #null values in review ratings are replaced by avg review rating

0

In [60]:
print(df.duplicated().sum())

df.drop_duplicates() #if present

0

In [3]:
df = df.rename(columns = {'Purchase Amount (USD)' : 'Purchase Amount'})
print(df.columns.tolist())

['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases', 'Age_group']

In [2]:
def age_group (age):
    if age < 25 :
        return 'younger (less than 25)'
    elif age < 45:
        return 'Middle (<45)'
    else:
        return 'Senior(45 above)'
df['Age_group'] = df['Age'].apply(age_group)
df[['Age','Age_group']].head(5)

   Age               Age_group
0   55        Senior(45 above)
1   19  younger (less than 25)
2   50        Senior(45 above)
3   21  younger (less than 25)
4   45        Senior(45 above)

In [7]:
df['Spend levels'] = df['Purchase Amount'].apply(lambda x : 'High' if x >= 80 else 'Low' ) 
df[['Purchase Amount','Spend levels','Gender']].head(5)

   Purchase Amount Spend levels Gender
0               53          Low   Male
1               64          Low   Male
2               73          Low   Male
3               90         High   Male
4               49          Low   Male

In [13]:
df['Gender_upper'] = df['Gender'].str.upper()
df[['Gender_upper']].head(5)

  Gender_upper
0         MALE
1         MALE
2         MALE
3         MALE
4         MALE

In [17]:
df_sorted = df.sort_values('Purchase Amount',ascending = False)
df_sorted[['Customer ID','Purchase Amount']].head(5) #using sort

      Customer ID  Purchase Amount
2842         2843              100
95             96              100
581           582              100
1421         1422              100
3837         3838              100

In [25]:
df['Rank'] = df['Purchase Amount'].rank(method = 'dense',ascending=False)
df[df['Rank'] == 1][['Customer ID','Rank']].head(5) #using dense rank

     Customer ID  Rank
42            43   1.0
95            96   1.0
193          194   1.0
204          205   1.0
243          244   1.0

In [30]:
df['Season'].value_counts()

Season
Spring    999
Fall      975
Winter    971
Summer    955
Name: count, dtype: int64

In [34]:
df['Category'].unique() #array
df['Category'].unique().tolist() #list

['Clothing', 'Footwear', 'Outerwear', 'Accessories']

In [49]:
df.groupby('Category')['Purchase Amount'].sum().sort_values(ascending = False)

Category
Clothing       104264
Accessories     74200
Footwear        36093
Outerwear       18524
Name: Purchase Amount, dtype: int64

In [42]:
category_summary = df.groupby('Category')['Purchase Amount'].agg([
    ('total sales','sum'),
    ('average spend','mean')
]).round(2)

category_summary

             total sales  average spend
Category
Accessories        74200          59.84
Clothing          104264          60.03
Footwear           36093          60.26
Outerwear          18524          57.17

In [45]:
pivot = df.pivot_table(
    values='Purchase Amount',
    index='Season',
    columns='Gender',
    aggfunc='mean'
).round(2)

pivot #excel like table

Gender  FEMALE   MALE
Season
Fall     61.56  61.55
Spring   58.79  58.71
Summer   60.60  57.41
Winter   60.00  60.52

In [52]:
pd.crosstab(df['Gender'],df['Subscription Status'])

Subscription Status    No   Yes
Gender
FEMALE               1248     0
MALE                 1599  1053

In [55]:
df_purchase = df[['Customer ID', 'Purchase Amount', 'Category']].head(5)
df_ratings = df[['Customer ID', 'Review Rating', 'Gender']].head(5)

inner_merge = pd.merge(df_purchase,df_ratings, on = 'Customer ID', how = 'inner' )
inner_merge

   Customer ID  Purchase Amount  Category  Review Rating Gender
0            1               53  Clothing            3.1   MALE
1            2               64  Clothing            3.1   MALE
2            3               73  Clothing            3.1   MALE
3            4               90  Footwear            3.5   MALE
4            5               49  Clothing            2.7   MALE

In [66]:
df_top = df.head(5)
df_bottom = df.tail(5)

df_added = pd.concat([df_top,df_bottom], ignore_index = True)
print('shape:',df_added.shape)
df_added[['Customer ID', 'Purchase Amount', 'Category']]

shape: (10, 22)

   Customer ID  Purchase Amount     Category
0            1               53     Clothing
1            2               64     Clothing
2            3               73     Clothing
3            4               90     Footwear
4            5               49     Clothing
5         3896               28     Clothing
6         3897               49  Accessories
7         3898               33  Accessories
8         3899               77     Footwear
9         3900               81  Accessories

In [67]:
## BUSINESS INSIGHTS REAL WORLD ##

In [69]:
# do subscribers spend more than non-subscribers?
df.groupby('Subscription Status')['Purchase Amount'].mean().round(2)

Subscription Status
No     59.87
Yes    59.49
Name: Purchase Amount, dtype: float64

In [ ]:
# Full Summary ##

In [79]:
print('*' * 50)
print('      CUSTOMER SHOPPING BUSINESS SUMMARY')
print('*' * 50)

print(f"Total Customers      : {len(df)}")
print(f"Total Revenue        : ${df['Purchase Amount'].sum():,.0f}")
print(f"Average Spend        : ${df['Purchase Amount'].mean():.2f}")
print(f"Avg Review Rating    : {df['Review Rating'].mean():.2f} / 5")
print(f"Top Category         : {df.groupby('Category')['Purchase Amount'].sum().idxmax()}")
print(f"Top Season           : {df.groupby('Season')['Purchase Amount'].sum().idxmax()}")
print(f"Top Payment Method   : {df['Payment Method'].value_counts().index[0]}")
print('*' * 50)

**************************************************
      CUSTOMER SHOPPING BUSINESS SUMMARY
**************************************************
Total Customers      : 3900
Total Revenue        : $233,081
Average Spend        : $59.76
Avg Review Rating    : 3.75 / 5
Top Category         : Clothing
Top Season           : Fall
Top Payment Method   : PayPal
**************************************************